// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/storage/uploader.go

// Package mock_storage is a generated GoMock package.
package mock_storage

import (
	gomock "github.com/golang/mock/gomock"
)
