// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/persistence/task.go

// Package mock_persistence is a generated GoMock package.
package mock_persistence

import (
	gomock "github.com/golang/mock/gomock"
)
