// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/board.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	domain "github.com/16francs/gran/api/todo/internal/domain"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockBoardService is a mock of BoardService interface
type MockBoardService struct {
	ctrl     *gomock.Controller
	recorder *MockBoardServiceMockRecorder
}

// MockBoardServiceMockRecorder is the mock recorder for MockBoardService
type MockBoardServiceMockRecorder struct {
	mock *MockBoardService
}

// NewMockBoardService creates a new mock instance
func NewMockBoardService(ctrl *gomock.Controller) *MockBoardService {
	mock := &MockBoardService{ctrl: ctrl}
	mock.recorder = &MockBoardServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBoardService) EXPECT() *MockBoardServiceMockRecorder {
	return m.recorder
}

// Index mocks base method
func (m *MockBoardService) Index(ctx context.Context, groupID string) ([]*domain.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", ctx, groupID)
	ret0, _ := ret[0].([]*domain.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Index indicates an expected call of Index
func (mr *MockBoardServiceMockRecorder) Index(ctx, groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockBoardService)(nil).Index), ctx, groupID)
}

// Show mocks base method
func (m *MockBoardService) Show(ctx context.Context, groupID, boardID string) (*domain.Board, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Show", ctx, groupID, boardID)
	ret0, _ := ret[0].(*domain.Board)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Show indicates an expected call of Show
func (mr *MockBoardServiceMockRecorder) Show(ctx, groupID, boardID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Show", reflect.TypeOf((*MockBoardService)(nil).Show), ctx, groupID, boardID)
}

// Create mocks base method
func (m *MockBoardService) Create(ctx context.Context, groupID string, b *domain.Board) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, groupID, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockBoardServiceMockRecorder) Create(ctx, groupID, b interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBoardService)(nil).Create), ctx, groupID, b)
}

// UploadThumbnail mocks base method
func (m *MockBoardService) UploadThumbnail(ctx context.Context, data []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadThumbnail", ctx, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadThumbnail indicates an expected call of UploadThumbnail
func (mr *MockBoardServiceMockRecorder) UploadThumbnail(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadThumbnail", reflect.TypeOf((*MockBoardService)(nil).UploadThumbnail), ctx, data)
}
