// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/validation/board.go

// Package mock_validation is a generated GoMock package.
package mock_validation

import (
	gomock "github.com/golang/mock/gomock"
)
