# ビルド用コンテナ
FROM golang:1.13.5-alpine as builder

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

WORKDIR /go/src/github.com/16francs/gran/api/user

RUN apk add --no-cache \
      git \
      make

ADD ./api/user ./
RUN make build

# 実行用コンテナ
FROM alpine

RUN apk add --no-cache \
      ca-certificates

COPY --from=builder /go/src/github.com/16francs/gran/api/user/app ./app

EXPOSE 8080
CMD ["./app"]
