// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/validation/task.go

// Package mock_validation is a generated GoMock package.
package mock_validation

import (
	request "github.com/calmato/gran/api/todo/internal/application/request"
	domain "github.com/calmato/gran/api/todo/internal/domain"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockTaskRequestValidation is a mock of TaskRequestValidation interface
type MockTaskRequestValidation struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRequestValidationMockRecorder
}

// MockTaskRequestValidationMockRecorder is the mock recorder for MockTaskRequestValidation
type MockTaskRequestValidationMockRecorder struct {
	mock *MockTaskRequestValidation
}

// NewMockTaskRequestValidation creates a new mock instance
func NewMockTaskRequestValidation(ctrl *gomock.Controller) *MockTaskRequestValidation {
	mock := &MockTaskRequestValidation{ctrl: ctrl}
	mock.recorder = &MockTaskRequestValidationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTaskRequestValidation) EXPECT() *MockTaskRequestValidationMockRecorder {
	return m.recorder
}

// CreateTask mocks base method
func (m *MockTaskRequestValidation) CreateTask(req *request.CreateTask) []*domain.ValidationError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", req)
	ret0, _ := ret[0].([]*domain.ValidationError)
	return ret0
}

// CreateTask indicates an expected call of CreateTask
func (mr *MockTaskRequestValidationMockRecorder) CreateTask(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskRequestValidation)(nil).CreateTask), req)
}
